[package]
authors = ['enpitsulin <enpitsulin@gmail.com>']
description = "明日方舟MMA助手的rust绑定"
edition = "2021"
license = "MIT"
name = "maa"
repository = "https://github.com/enpitsuLin/maa-asst-rs"
version = "0.1.0"

[dependencies]
libc = "0.2"

[build-dependencies]
glob = "0.3"

[lib]
name = "maa"

[[example]]
name = "example"
path = "example/example.rs"

[[example]]
name = "create_ex"
path = "example/create_ex.rs"
